-- Creating function
DROP FUNCTION IF EXISTS SafeDiv;

DELIMITER / /

CREATE FUNCTION SafeDiv(a INT, b INT)
RETURNS DECIMAL(10, 6)
BEGIN
    IF b = 0 THEN
        RETURN 0;
    END IF;
    RETURN a / b;
END //

DELIMITER;